server:
  port: 9001
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbdoublevpartners
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    database: POSTGRESQL
    show-sql : true
    hibernate:
      ddl-auto: update
